services:
  control_node:
    build: .
    container_name: control_node
    hostname: control_node
    privileged: true
    networks:
      lab_net:
        ipv4_address: 192.168.20.101
    volumes:
      - ./playbooks:/root/ansible_project # Pour persister vos playbooks

  env_builder:
    build: .
    container_name: env_builder
    hostname: env_builder
    networks:
      lab_net:
        ipv4_address: 192.168.20.102
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  test_runner:
    build: .
    container_name: test_runner
    hostname: test_runner
    networks:
      lab_net:
        ipv4_address: 192.168.20.103

  logs_manager:
    build: .
    container_name: logs_manager
    hostname: logs_manager
    networks:
      lab_net:
        ipv4_address: 192.168.20.104
    ports:
      - "5601:3000"

  dashboard:
    build: .
    container_name: dashboard
    hostname: dashboard
    networks:
      lab_net:
        ipv4_address: 192.168.20.105
    ports:
      - "3000:3000"

networks:
  lab_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.20.0/24

